### ISSUE TITLE
Add a user to the manifest template (manifest.tmpl)

### ISSUE THREAD

**Issue by chorrell** [joyent/joyent-retro#1]
The SmartOS image has been super helpful for building lx-brand images. Once small improvement I'd like to recommend is to add a root user to the manifest.tmpl image manifest template:

```
"users": [{"name": "root"}]
```

This is helpful for when you want to use the triton cli to ssh in:

```
triton ssh UUID
```

The CLI (I think) uses that to determine what usr to ssh in as and without that set, it fails:

```
$ triton ssh smartos-kvm-01-us-east-1
/usr/local/lib/node_modules/triton/lib/do_instance/do_ssh.js:79
                if (image.tags.default_user) {
                              ^

TypeError: Cannot read property 'default_user' of undefined
    at /usr/local/lib/node_modules/triton/lib/do_instance/do_ssh.js:79:31
    at done (/usr/local/lib/node_modules/triton/lib/tritonapi.js:603:17)
    at next (/usr/local/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:201:4)
    at Object.cloudApiGetImage [as func] (/usr/local/lib/node_modules/triton/lib/tritonapi.js:587:21)
    at Immediate._onImmediate (/usr/local/lib/node_modules/triton/node_modules/vasync/lib/vasync.js:213:20)
    at processImmediate [as _immediateCallback] (timers.js:396:17)
```

The triton cli should probably fall back to assuming root, but having that set in the manifest is still a good idea.

**Comment by bahamat** [comment]
SSH isn't an issue these days. I'm not sure when the behavior changed, but this can be closed.
